version: '3.5'

services:
  backend_app:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    working_dir: /code
    command: flask run
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/code
      - /code/songs
    ports:
      - 5000:5000

  frontend_app:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    working_dir: /code/app
    command: npm start
    volumes:
      - ./frontend:/code/app:delegated
      - ./frontend/package.json:/code/package.json
      - ./frontend/package-lock.json:/code/package-lock.json
      - /code/app/node_modules
    ports:
      - 1234:1234
      - 2345:2345