version: '3.5'

services:
  backend_app:
    build:
      context: ./
      dockerfile: backend.Dockerfile
    working_dir: /code
    command: flask run
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/code    
    ports:
      - 5000:5000

  frontend_app:
    build:
      context: ./
      dockerfile: frontend.Dockerfile
    working_dir: /code
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - 1234:1234
